### PR TITLE
Add support for >=tsdl.0.9.0 through result type

### PR DESCRIPTION
**Pull request by dagoof**
Thanks for creating this package; it would be great to get to get this onto opam.

I'm not sure why the travis ci build is failing; no rakefile?

### CODE REVIEW

**Comment by tokenrove** [comment]
Thanks for the PR both here and on tsdl-image!  If you don't mind, it may take me a day or two to get to reviewing and approving them.

Sorry for the failing Travis builds; in this case I appear to have switched on Travis without providing a travis.yml file.

**Comment by dagoof** [comment]
That's totally fine, I'm pretty new to contributing publicly to ocaml -- so if the style is off or I've done something wrong let me know and I'm happy to update

**Comment by tokenrove** [comment]
This looks good.  My only corrective comments were going to be about formatting, but then I noticed that I had also screwed up the formatting at one point.  (I will say anyway: be sure to use merlin and ocp-indent.)  So I'll just touch that up before making a release.

If you don't mind waiting another day or two, I'm going to make the same changes to tsdl-mixer and update the things I've written using these libraries, to make sure that everything makes sense.

**Comment by dagoof** [comment]
That sounds great!

Sorry, I don't have mixer used in any projects yet or I would have updated that as well. Thanks for taking the time to look over it

**Comment by tokenrove** [comment]
Thanks.  Your contribution has been merged and I have submitted this release to OPAM: https://github.com/ocaml/opam-repository/pull/8273

**Pull request merged**
